"use client";

import ContentContainer from "@/components/layout/contentContainer";
import LedGrid from "@/components/ledGrid";
import ProjectCard from "@/components/projectCard";
import { WORK_DESCRIPTIONS } from "@/constants/descriptions";
import { INTERNAL_LINK, WORK_LINK } from "@/constants/links";
import Image from "next/image";

const Page = () => {
  return (
    <ContentContainer>
      <div className="flex flex-col w-full justify-center items-center gap-12 mb-[100px]">
        <div className="max-w-[400px] mx-auto w-full my-5 md:my-8">
          <LedGrid value={"WORK"} gridStyle="grid-cols-4" delay={50} />
        </div>
        <ProjectCard
          wordmark={
            <img
              className="w-full opacity-90"
              src="/assets/ensemble/wordmark.png"
              alt="Ensemble"
            />
          }
          headline={WORK_DESCRIPTIONS.ensemble.headline}
          headingOne="Involvement"
          paragraphOne={
            <>
              <span className="font-bold">
                - {WORK_DESCRIPTIONS.ensemble.role}&nbsp;&nbsp;
              </span>
              <span className="font-extralight tracking-wider">
                ({WORK_DESCRIPTIONS.ensemble.date})
              </span>
              <br />
              <span>- {WORK_DESCRIPTIONS.ensemble.involvementSummary}</span>
            </>
          }
          headingTwo="Summary"
          paragraphTwo={WORK_DESCRIPTIONS.ensemble.summary}
          internalLink={INTERNAL_LINK.WORK + WORK_LINK.ENSEMBLE}
        >
          <div className="gap-2 w-full flex mx-auto flex-col">
            <Image
              alt="Game Assets"
              src="/assets/ensemble/game-assets.png"
              className="object-scale-down w-full rounded-xl border brightness-[99%] hover:brightness-100"
              width={1600}
              height={900}
            />
            <p className="font-mono text-center text-sm font-extralight">
              Game assets on Ensemble
            </p>
            <div className="hidden md:contents">
              <Image
                alt="Explore page"
                src="/assets/ensemble/artifact-explore-page.png"
                className="object-scale-down w-full rounded-xl border mt-4 brightness-[99%] hover:brightness-100 transition duration-300"
                width={1600}
                height={900}
              />
              <p className="font-mono text-center text-sm font-extralight">
                Sketches on Ensemble
              </p>
            </div>
          </div>
        </ProjectCard>
        <ProjectCard
          wordmark={
            <img
              className="w-full max-w-[150px] mx-auto opacity-90"
              src="/assets/tapp/wordmark.png"
              alt="Tapp"
            />
          }
          headline={WORK_DESCRIPTIONS.tapp.headline}
          headingOne="Involvement"
          paragraphOne={
            <>
              <span className="font-bold">
                - {WORK_DESCRIPTIONS.tapp.role}&nbsp;&nbsp;
              </span>
              <span className="font-extralight tracking-wider">
                ({WORK_DESCRIPTIONS.tapp.date})
              </span>
              <br />
              <span>- {WORK_DESCRIPTIONS.tapp.involvementSummary}</span>
            </>
          }
          headingTwo="Summary"
          paragraphTwo={WORK_DESCRIPTIONS.tapp.summary}
          internalLink={INTERNAL_LINK.WORK + WORK_LINK.TAPP}
        >
          <div className="gap-2 w-full flex mx-auto flex-col">
            <Image
              alt="Landing page"
              src="/assets/tapp/tools-with-device.png"
              className="object-scale-down w-full rounded-xl border brightness-[99%] hover:brightness-100"
              width={1600}
              height={900}
            />
            <p className="font-mono text-center text-sm font-extralight">
              Tapp toolkit and device mockup
            </p>
            <div className="hidden md:contents">
              <Image
                alt="Explore page"
                src="/assets/tapp/data-graphics.png"
                className="object-scale-down w-full rounded-xl mt-4 brightness-[99%] hover:brightness-100 transition duration-300"
                width={1600}
                height={900}
              />
              <p className="font-mono text-center text-sm font-extralight">
                Data graphics generated by Tapp
              </p>
            </div>
          </div>
        </ProjectCard>
      </div>
    </ContentContainer>
  );
};

export default Page;
